export const USER_START = "USER_START";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAIL = "USER_FAIL";

export const FETCH_REPO_START = "FETCH_REPO_START";
export const FETCH_REPO_SUCCESS = "FETCH_REPO_SUCCESS";
export const FETCH_REPO_FAIL = "FETCH_REPO_FAIL";
export const FETCH_SEARCH_LIST = "FETCH_SEARCH_LIST";
