export const USER_SUCCESS = "USER_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGIN = "USER_LOGIN";
export const USER_AUTO_SIGNIN = "USER_AUTO_SIGNIN";

export const FETCH_REPO_SUCCESS = "FETCH_REPO_SUCCESS";
export const FETCH_SEARCH_LIST = "FETCH_SEARCH_LIST";
export const FETCH_SEARCH = "FETCH_SEARCH";
export const FETCH_LIST = "FETCH_LIST";
